dist: trusty
sudo: required

language: c

matrix:
  include:
   - os: linux
   - os: osx
     osx_image: Xcode 8.3.3
   - os: osx
     osx_image: Xcode 7.3.1
   - os: osx
     osx_image: xcode6.4

  allow_failures:
   - os: osx
     osx_image: xcode6.4

before_install:
  - sleep 3 #give xvfb some time to start
  - rm -rf ~/home/.enthought
  - make deps 
  - pip list

before_script:
  - "export DISPLAY=:0.0"
  - "export PATH=/usr/local/bin/:./:$PATH"
  - Xvfb :0.0 -screen 1 800x600x16 &
  - sleep 3

script:
  - tox
  - rm -rf ~/home/.enthought
  - PYTHONPATH=. python piksi_tools/console/console.py --file --error -p ./tests/data/piksi.bin & PID=$!
  - sleep 10 
  - kill -n 9  $PID
  - PYTHONPATH=. python piksi_tools/console/console.py --file --error -p ./tests/data/20170513-180207.1.1.26.bin & PID=$!
  - sleep 10 
  - kill -n 9  $PID
  - make build_console
  - sudo python setup.py install
  - export GIT_DESCRIBE=`git describe`

cache:
  directories:
    - $HOME/.cache/pip/
    - /Library/Caches/Homebrew/

addons:
  artifacts:
    debug: true 
    paths:
      - $(ls ./piksi_tools/console/pyinstaller/dist/swift_console* | tr "\n" ":")
      - ./piksi_tools/console/pyinstaller/build
    working_dir: $TRAVIS_BUILD_DIR
    target_paths: $GIT_DESCRIBE$TRAVIS_PULL_REQUEST_BRANCH_$TRAVIS_OS_NAME
    bucket: console-ci-builds
    s3_region: us-west-2
deploy:
  provider: pypi
  user: mark.fine@gmail.com
  password:
    secure: ieClfaRbsPwbrSIvxPw4BPJr907iYrTembEVTyHt506/lRO2ps2F6QOoMqv/LV3HWHCV01mPUM1fdOaGrs/mtrCtrBDHV6nb1En/u46g7R/lHnqkfVdo+Mu+z0Pfpd+WIGsUu8KxSNdT2TKvyVelhlqnLgksjvEc7RjXpDdPc7s=
  on:
    tags: true
    all_branches: true
notifications:
  email: false
  slack:
    secure: c/HX84/BjWHU/8LmtES2fh7lFiXwXnRJnwjCYjLw85M/Po2PYkGRkwk+o5BTX2cei9+QkXGxLcyCYZtMbRU0nN2S6t5Va7WaZulmFtqgnjn4eTxtdctk0Gk5nDB8qUuruxo8F5qki6z86UtRQzr0Ms52GZbUhLPsJTCsXZRyvk0=
